Building UI with email view
meu-pix-facil/web-site pull request #5
Opened 2020-12-30 04:30 UTC by victorabarros

2021-01-01 07:10 UTC, fernando-ringba commented on user-interface/pages/confirmation.js
> +          e enviar o comprovante para o mesmo email.
No need to send the receipt, it is possible to add a note to the pix transfer, clients can use this note to identify themselves.

2021-01-03 22:23 UTC, fernando-ringba commented on user-interface/components/Form.js
> +    'victorbarros.com.br', // TODO remove
lets use only meupixfacil.com initially

2021-01-03 22:26 UTC, fernando-ringba commented on user-interface/components/Form.js
> +      console.log(error);
we should log errors in a file, no?

2021-01-03 22:31 UTC, fernando-ringba commented on user-interface/pages/confirmation.js
> +          sua identificação na descrição.
```suggestion
          Agora só resta fazer um PIX de R$79 para meupixfacil@meupixfacil.com adicionando seu email na descrição do PIX.
```

2021-01-03 22:32 UTC, fernando-ringba commented on user-interface/components/Form.js
> +  };
There are components that can be used to take care of the validation.

2021-01-03 22:33 UTC, fernando-ringba commented on user-interface/service/api.js
> +    console.log(error);
we should log errors in a file

2021-01-03 22:34 UTC, fernando-ringba requested changes
Check comments.

2021-01-04 00:44 UTC, victorabarros commented on user-interface/components/Form.js
> +      console.log(error);
It will be solve at #12

2021-01-04 00:47 UTC, victorabarros commented on user-interface/components/Form.js
> +  };
We need to improve with better tools then regex.
https://react-hook-form.com/
https://medium.com/@adostes/validating-a-form-in-react-cc29d47e140f

2021-01-04 00:53 UTC, fernando-ringba approved these changes

2021-01-04 00:53 UTC, merged